# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-05 16:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsRelationsShip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_index', models.IntegerField(default=0)),
                ('common_tags', models.TextField(default='[]')),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.BaseModel')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=400)),
            ],
            bases=('api.basemodel',),
        ),
        migrations.CreateModel(
            name='FootballMatchCommentary',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.BaseModel')),
                ('current_play_time_status', models.CharField(choices=[('FIRST_HALF', 'VERIFY_EMAIL'), ('RESET_PASSWORD', 'RESET_PASSWORD')], max_length=200, null=True)),
                ('added_time', models.CharField(blank=True, max_length=200, null=True)),
                ('comment', models.TextField()),
                ('is_key_event', models.BooleanField(default=False)),
            ],
            bases=('api.basemodel',),
        ),
        migrations.CreateModel(
            name='FootBallMatchDetails',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.BaseModel')),
                ('match_starting_date', models.DateField(blank=True, db_index=True, null=True)),
                ('match_finishing_date', models.DateField(blank=True, null=True)),
                ('match_starting_time', models.TimeField(blank=True, null=True)),
                ('match_finishing_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('UPCOMING', 'VERIFY_EMAIL'), ('STARTED', 'RESET_PASSWORD'), ('FINISHED', 'RESET_PASSWORD'), ('POSTPONED', 'RESET_PASSWORD'), ('DELAYED', 'RESET_PASSWORD'), ('DRAW', 'RESET_PASSWORD')], db_index=True, max_length=200)),
                ('current_status_text', models.CharField(blank=True, max_length=200, null=True)),
                ('match_facts', models.TextField(blank=True, null=True)),
                ('match_description', models.TextField(blank=True, null=True)),
                ('venue', models.TextField()),
                ('postponed_date', models.DateField(blank=True, null=True)),
                ('postponed_time', models.TimeField(blank=True, null=True)),
                ('concise_summary_text', models.TextField(blank=True, null=True)),
                ('current_play_time_status', models.CharField(choices=[('FIRST_HALF', 'VERIFY_EMAIL'), ('RESET_PASSWORD', 'RESET_PASSWORD')], max_length=200, null=True)),
                ('sport', models.CharField(choices=[('FOOTBALL', 'VERIFY_EMAIL')], max_length=200)),
                ('team_one_score', models.IntegerField(default=0)),
                ('team_two_score', models.IntegerField(default=0)),
            ],
            bases=('api.basemodel',),
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.BaseModel')),
                ('news_date', models.DateField(db_index=True)),
                ('content', models.TextField()),
                ('source', models.CharField(max_length=200)),
                ('title', models.TextField()),
                ('tags', models.TextField(default='[]')),
                ('sport', models.CharField(choices=[('FOOTBALL', 'VERIFY_EMAIL')], max_length=200)),
                ('is_trending', models.BooleanField(default=False)),
                ('trend_scale', models.IntegerField(blank=True, null=True)),
                ('number_of_likes', models.IntegerField(default=0)),
                ('number_of_dislikes', models.IntegerField(default=0)),
                ('number_of_views', models.IntegerField(default=0)),
            ],
            bases=('api.basemodel',),
        ),
        migrations.CreateModel(
            name='NewsTags',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.BaseModel')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            bases=('api.basemodel',),
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.BaseModel')),
                ('name', models.CharField(max_length=200)),
                ('sport', models.CharField(choices=[('FOOTBALL', 'VERIFY_EMAIL')], db_index=True, max_length=200)),
                ('biography', models.TextField()),
            ],
            bases=('api.basemodel',),
        ),
        migrations.CreateModel(
            name='SportsMatch',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.BaseModel')),
                ('match_starting_date', models.DateField(db_index=True)),
                ('match_starting_time', models.TimeField()),
                ('match_finishing_date', models.DateField()),
                ('match_finishing_time', models.TimeField()),
                ('status', models.CharField(choices=[('UPCOMING', 'VERIFY_EMAIL'), ('STARTED', 'RESET_PASSWORD'), ('FINISHED', 'RESET_PASSWORD'), ('POSTPONED', 'RESET_PASSWORD'), ('DELAYED', 'RESET_PASSWORD'), ('DRAW', 'RESET_PASSWORD')], db_index=True, max_length=200)),
                ('match_facts', models.TextField(null=True)),
                ('match_description', models.TextField()),
                ('venue', models.TextField()),
                ('postponed_date', models.DateField()),
                ('postponed_time', models.TimeField()),
                ('concise_summary_text', models.TextField()),
                ('sport', models.CharField(choices=[('FOOTBALL', 'VERIFY_EMAIL')], db_index=True, max_length=200)),
            ],
            bases=('api.basemodel',),
        ),
        migrations.CreateModel(
            name='SportTeam',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.BaseModel')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('sport', models.CharField(choices=[('FOOTBALL', 'VERIFY_EMAIL')], db_index=True, max_length=200)),
            ],
            bases=('api.basemodel',),
        ),
        migrations.AddField(
            model_name='sportsmatch',
            name='team_one',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.SportTeam'),
        ),
        migrations.AddField(
            model_name='sportsmatch',
            name='team_two',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.SportTeam'),
        ),
        migrations.AddField(
            model_name='sportsmatch',
            name='team_won',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.SportTeam'),
        ),
        migrations.AddField(
            model_name='newsrelationsship',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.News'),
        ),
        migrations.AddField(
            model_name='newsrelationsship',
            name='related_news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.News'),
        ),
        migrations.AddField(
            model_name='news',
            name='related_news',
            field=models.ManyToManyField(blank=True, related_name='_news_related_news_+', through='api.NewsRelationsShip', to='api.News'),
        ),
        migrations.AddField(
            model_name='footballmatchdetails',
            name='team_one',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.SportTeam'),
        ),
        migrations.AddField(
            model_name='footballmatchdetails',
            name='team_two',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.SportTeam'),
        ),
        migrations.AddField(
            model_name='footballmatchdetails',
            name='team_won',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.SportTeam'),
        ),
        migrations.AddField(
            model_name='footballmatchcommentary',
            name='football_match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaries', to='api.FootBallMatchDetails'),
        ),
    ]
