# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-12 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footballmatchcommentary',
            old_name='comment',
            new_name='commentary_content',
        ),
        migrations.RemoveField(
            model_name='footballmatchcommentary',
            name='added_time',
        ),
        migrations.AddField(
            model_name='footballmatchcommentary',
            name='commentary_heading',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='footballmatchcommentary',
            name='current_play_time_status',
            field=models.CharField(blank=True, choices=[('FIRST_HALF', 'VERIFY_EMAIL'), ('RESET_PASSWORD', 'RESET_PASSWORD')], max_length=200, null=True),
        ),
    ]
