# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-08 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='footballmatchdetails',
            name='display_priority_scale',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='footballmatchdetails',
            name='is_kerala_blasters_involved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='footballmatchdetails',
            name='match_title',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='footballmatchdetails',
            name='should_show_on_home_page',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='news',
            name='home_page_display_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='news',
            name='news_date_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='should_display_on_home_page',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sportteam',
            name='identifier',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='footballmatchdetails',
            name='status',
            field=models.CharField(choices=[('UPCOMING', 'MATCH_STATUS'), ('STARTED', 'STARTED'), ('FINISHED', 'FINISHED'), ('POSTPONED', 'POSTPONED'), ('DELAYED', 'DELAYED'), ('DRAW', 'DRAW')], db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='sportsmatch',
            name='status',
            field=models.CharField(choices=[('UPCOMING', 'MATCH_STATUS'), ('STARTED', 'STARTED'), ('FINISHED', 'FINISHED'), ('POSTPONED', 'POSTPONED'), ('DELAYED', 'DELAYED'), ('DRAW', 'DRAW')], db_index=True, max_length=200),
        ),
    ]
