# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-12 15:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171112_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('jersey_number', models.IntegerField(blank=True, null=True)),
                ('player_role', models.CharField(choices=[('CAPTAIN', 'CAPTAIN'), ('VICE_CAPTAIN', 'VICE_CAPTION'), ('GOAL_KEEPER', 'GOAL_KEEPER'), ('NORMAL', 'NORMAL')], default='NORMAL', max_length=200)),
                ('position', models.CharField(blank=True, max_length=200, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='api.FootBallMatchDetails')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='footballmatchcommentary',
            name='current_play_time_status',
            field=models.CharField(blank=True, choices=[('FIRST_HALF', 'FIRST_HALF'), ('SECOND_HALF', 'FIRST_HALF'), ('EXTRA_TIME', 'EXTRA TIME'), ('INJURY_TIME', 'INJURY_TIME')], max_length=200, null=True),
        ),
    ]
