# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-09 01:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171108_2355'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchSeries',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.BaseModel')),
                ('display_name', models.CharField(max_length=200)),
                ('identifier', models.CharField(max_length=200, unique=True)),
            ],
            bases=('api.basemodel',),
        ),
        migrations.AddField(
            model_name='footballmatchdetails',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='api.SportTeam'),
        ),
    ]
