# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-09 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20171109_0121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footballmatchdetails',
            options={'ordering': ('created_at',)},
        ),
        migrations.AlterModelOptions(
            name='matchseries',
            options={'ordering': ('display_name',)},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('created_at',)},
        ),
        migrations.AlterModelOptions(
            name='newstags',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='sportsmatch',
            options={'ordering': ('created_at',)},
        ),
        migrations.AlterModelOptions(
            name='sportteam',
            options={'ordering': ('display_name',)},
        ),
        migrations.RenameField(
            model_name='sportteam',
            old_name='name',
            new_name='display_name',
        ),
        migrations.AlterField(
            model_name='sportteam',
            name='identifier',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
