# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-12 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20171112_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchplayer',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
