# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-15 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20171114_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestnews',
            name='identifier',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
