# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-09 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20171109_0138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newstags',
            options={'ordering': ('tag_name',)},
        ),
        migrations.RenameField(
            model_name='newstags',
            old_name='name',
            new_name='tag_name',
        ),
        migrations.AddField(
            model_name='news',
            name='related_tags',
            field=models.ManyToManyField(blank=True, related_name='_news_related_tags_+', to='api.NewsTags'),
        ),
        migrations.AlterField(
            model_name='footballmatchdetails',
            name='sport',
            field=models.CharField(choices=[('FOOTBALL', 'FOOTBALL')], max_length=200),
        ),
        migrations.AlterField(
            model_name='news',
            name='sport',
            field=models.CharField(choices=[('FOOTBALL', 'FOOTBALL')], max_length=200),
        ),
        migrations.AlterField(
            model_name='players',
            name='sport',
            field=models.CharField(choices=[('FOOTBALL', 'FOOTBALL')], db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='sportsmatch',
            name='sport',
            field=models.CharField(choices=[('FOOTBALL', 'FOOTBALL')], db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='sportteam',
            name='sport',
            field=models.CharField(choices=[('FOOTBALL', 'FOOTBALL')], db_index=True, max_length=200),
        ),
    ]
