# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-25 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_guestnews_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='footballmatchcommentary',
            name='tag',
            field=models.CharField(blank=True, choices=[('YELLOW_CARD', 'YELLOW_CARD'), ('RED_CARD', 'RED_CARD'), ('SUBSTITUTION', 'SUBSTITUTION'), ('GOAL', 'GOAL'), ('EXTRA_MINUTE', 'EXTRA_MINUTE')], max_length=200, null=True),
        ),
    ]
