# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-12 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20171112_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='trend_scale',
            field=models.IntegerField(default=0),
        ),
    ]
