# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-25 09:59
from __future__ import unicode_literals

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_footballmatchcommentary_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='footballmatchdetails',
            name='lineup_image',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.get_match_line_up_image_path),
        ),
        migrations.AddField(
            model_name='matchseries',
            name='logo_image',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.get_series_logo_image_path),
        ),
    ]
