# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-25 11:12
from __future__ import unicode_literals

import api.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20171125_0959'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentaryTagImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tag', models.CharField(blank=True, choices=[('YELLOW_CARD', 'YELLOW_CARD'), ('RED_CARD', 'RED_CARD'), ('SUBSTITUTION', 'SUBSTITUTION'), ('GOAL', 'GOAL'), ('EXTRA_MINUTE', 'EXTRA_MINUTE')], max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=api.models.get_series_logo_image_path)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
