# email
FROM_EMAIL = 'support@malayalamsports.com'

# status
STATUS_SUCCESS = 20
STATUS_INVALID_REQUEST = 40
STATUS_SERVER_ERROR = 50

# news
NUMBER_OF_TRENDING_NEWS = 4
NUMBER_OF_NEWS_DISPLAYED_IN_WEB_HOME_PAGE = 2

LOGGER_NAME = 'api'

# roles
SUPER_ADMIN = 'SUPER_ADMIN'
CLIENT_ADMIN = 'CLIENT_ADMIN'
USER = 'USER'

CURRENT_VERSION = 'v1'
ALLOWED_VERSION = ['v1']

# context

UPDATE_CONTEXT = 'update'
CREATE_CONTEXT = 'create'
LISTING_CONTEXT = 'list'
DETAIL_CONTEXT = 'list'

# token types
VERIFY_EMAIL_TOKEN = 'VERIFY_EMAIL'
RESET_PASSWORD_TOKEN = 'RESET_PASSWORD'

# token expiry in hour
VERIFY_EMAIL_TOKEN_EXPIRY = 24
RESET_PASSWORD_TOKEN_EXPIRY = 24

LOGO_IMAGE_ALLOWED_FORMATS = [
    "jpg",
    "jpeg",
    "png",
]

FAVICON_IMAGE_ALLOWED_FORMATS = [
    "ico",
    "png",
    "gif",
    "jepg",
    "vnd.microsoft.icon",
]

VALID_IMAGE_MIMETYPES = [
    "image"
]

# response dict keys

ERROR_RESPONSE_KEY_SESSION = 'session'
RESPONSE_KEY_VERSION = 'version'
RESPONSE_USER_AGENT = 'user_agent'
ERROR_RESPONSE_KEY_AUTHORIZATION = 'authorization'
ERROR_RESPONSE_KEY_REQUEST = 'request'
ERROR_RESPONSE_KEY_MESSAGE = 'message'
RESPONSE_DICT_RESULT_KEY = 'result'
ERROR_RESPONSE_KEY_EXCEPTION = 'exception'
ERROR_RESPONSE_KEY_VALIDATION = 'validation'
ERROR_RESPONSE_KEY_FORBIDDEN = 'forbidden'

ERROR_DICT_KEY_TYPE = 'error_type'
ERROR_DICT_KEY_DISPLAY_MESSAGE = 'display_message'
ERROR_DICT_KEY_DETAIL = 'detail'

# account

PASSWORD_MIN_LENGTH = 4
PASSWORD_MAX_LENGTH = 30

# enums

MATCH_STATUS = (
    ('UPCOMING', 'MATCH_STATUS'),
    ('STARTED', 'STARTED'),
    ('FINISHED', 'FINISHED'),
    ('POSTPONED', 'POSTPONED'),
    ('DELAYED', 'DELAYED'),
    ('DRAW', 'DRAW')

)

# match status
MATCH_STATUS_UPCOMING = 'UPCOMING'
MATCH_STATUS_STARTED = 'STARTED'
MATCH_STATUS_FINISHED = 'FINISHED'
MATCH_STATUS_POSTPONED = 'POSTPONED'
MATCH_STATUS_DELAYED = 'DELAYED'
MATCH_STATUS_DRAW = 'DRAW'

CURRENT_PLAY_TIME = (
    ('FIRST_HALF', 'FIRST_HALF'),
    ('SECOND_HALF', 'FIRST_HALF'),
    ('EXTRA_TIME', 'EXTRA TIME'),
    ('INJURY_TIME', 'INJURY_TIME'),
)

SPORT_CATEGORY = (
    ('FOOTBALL', 'FOOTBALL'),
)

PLAYER_ROLES = (
    ('CAPTAIN', 'CAPTAIN'),
    ('VICE_CAPTAIN', 'VICE_CAPTION'),
    ('GOAL_KEEPER', 'GOAL_KEEPER'),
    ('NORMAL', 'NORMAL'),
)

SPORTS_FOOTBALL = 'FOOTBALL'

# kerala blasters
KERLA_BLASTERS_TEAM_IDENTIFIER = 'KERALA_BLASTERS'
